### ISSUE TITLE
Problem with zones and sequences when more than one controller is present

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation-unlimited-card#1]
**Release with the issue:**

2022.4.1

**Last working release (if known):**

First version tried

**Browser and Operating System:**

Google Chrome Versión 100.0.4896.127 (Build oficial) (64 bits)

**Description of problem:**
 
I have two controllers in my configuration. The problem in the card is that if I show zones and sequences in second controller, it's shown information (zones and sequences) of the first controller. If I show zones and sequences in the first controller, the behaviour is the correct one.

Apart from that, the card is great. Thanks!

**Comment by Fox350** [comment]
Same issue,  Great work in progress but not for two controllers yet.  Continue your great work!

**Comment by kandrzejczak** [comment]
Same issue. @rgc99 You could take a look at this bug ?

**Comment by miguelpucela** [comment]
The issue is solved.

Thanks!
