### ISSUE TITLE
Irrigation card does not display zones or sequences anymore

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation-unlimited-card#10]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2024.1.0
HAOS: 2024.2.1
**Last working release (if known):**
2024.1.0
**Browser and Operating System:**
Win10, Edge, Brave, Firefox

**Description of problem:**

Card does not display anymore on the production machine. Exact same configuration loaded on my test machine as this screenshot shows is correctly displayed
![image](https://github.com/rgc99/irrigation-unlimited-card/assets/20872098/4ff04e15-549b-4f31-a628-f05b2b02bc10)

**Javascript errors shown in the web inspector (if applicable):**
No specific error. I clearly see that the card content is not populated, ie card content is empty, whereas on the test machine the content is indeed populated. I tried numerous ideas, like adding the card on a newly created dashboard, restarted HA, restarted PC, cleared cache, private navigation, etc. 
It just happened all of a sudden.
I'm just out of any idea and I'm at lost
Help will be much appreciated.

**Comment by evercape** [comment]
Hi Kolia,
I have no issues.
Try update to latest version. This is mine:
Core
2024.3.3
Supervisor
2024.03.1
Operating System
12.1
Frontend
20240307.0
Rgds
M

**Comment by Kolia56** [comment]
Thanks Martin, I just did and still the same. Just for the records, on the test machine as described above, there is no issue. I even loaded the full backup to the test machine and the companion card is displayed correctly. Both HA are running under VBox.

**Comment by evercape** [comment]
I use proxmox. No issue. Very weird. Maybe something else / other component causing it? Try disable everything else to test?

**Comment by Kolia56** [comment]
Very strange indeed. I'm restoring the most updated backup to the test machine to see how things are going. I may restore a few days ago backup to the prod machine to see whether it has an effect.

**Comment by Kolia56** [comment]
Renaming entity_ids of the binary sensors does impact the card. I just made the experiment by changing them manually. So I'm now quite sure that rename_entities was the culprit.

**Comment by evercape** [comment]
Well done for figuring it out. Did you have any funny names with white spaces or so? Maybe try no spaces and only characters and numbers. If that works a simple sanitizing function in the companion card might be required.

**Comment by Kolia56** [comment]
No no, no funny names. I just replaced the last two characters by the zone id number. For instance before it was binary_sensor.irrigation_unlimited_c1_z10 and after binary_sensor.irrigation_unlimited_c1_z2. No big deal

**Comment by evercape** [comment]
Hm maybe try something else. In particular if zone 2 already existed. Otherwise if that does not work then it might be some other issue in the companion card. I have not looked at it.

**Comment by Kolia56** [comment]
As a test I just renamed binary_sensor.irrigation_unlimited_c1_z14 to binary_sensor.irrigation_unlimited_c1_z1444. It breaks the card. Reverting to the value, card reappears.

**Comment by rgc99** [comment]
The card uses well known names i.e. `binary_sensor.irrigation_unlimited_c1_z1`. A discovery mechanism would need to be implemented to understand the new naming structure. In the meantime I will emphasise in the documentation that the `rename_entities` setting will also break the card.

**Comment by Kolia56** [comment]
thank you. you may have noticed that in my case the naming structure was kept, only the value attached to z has been changed

**Comment by ricardofma** [comment]
Hello Everyone. I got the same issue as described above. I did not rename entities. It just stop being populated. I already delete the configuration file to a very basic script and it keeps not working. HACS and irrigation unlimited are all updated.

![configuration yaml](https://github.com/rgc99/irrigation-unlimited-card/assets/14083169/4a4e809a-5170-40ae-8821-0e80bbf894b0)
![irr](https://github.com/rgc99/irrigation-unlimited-card/assets/14083169/6e65abe8-9759-4ed6-95a5-66ea8532ee6a)
![irr2](https://github.com/rgc99/irrigation-unlimited-card/assets/14083169/9d0db873-4ed5-48d1-adf3-2cba418efe87)
![lovelace](https://github.com/rgc99/irrigation-unlimited-card/assets/14083169/03cf851f-999c-4bd7-9992-06bf254265ec)

**Comment by ricardofma** [comment]
I am getting crazy since I cannot solve this issue for many days! In the past everything is working! I don't know what made this stop working. 
Any help would be welcome! Many thanks!

**Comment by Kolia56** [comment]
> I am getting crazy since I cannot solve this issue for many days! In the past everything is working! I don't know what made this stop working. Any help would be welcome! Many thanks!

FWIW, and I know it is not going to be of great help, since I reverted back to the original entity IDs I did not have any issue. I run the latest versions of both extensions.
Did you try to restore backup at a point in time it was working on a separate machine. It could help you to understand what happened.

**Comment by ricardofma** [comment]
Thanks for your reply! But in fact I did not renamed it. I only created a single entity just to make a test. 
It is no longer working for many weeks.
If I make a restore backup I will make many changes I did in HA..:(

**Comment by Kolia56** [comment]
> If I make a restore backup I will make many changes I did in HA..:(

This is why I suggested to restore a backup to a test machine. If you can't, you could trigger a new backup, save it, restore an old backup, see whether your problem is still there and then restore the latest backup to resume normal operation.

**Comment by ricardofma** [comment]
Thanks for you suggestion. Give me your opinion on this:
Is there an option to totally remove the irrigation-unlimited from HACS and HA and ten reinstall it from zero?
What is the right way to do it?

**Comment by Kolia56** [comment]
> Thanks for you suggestion. Give me your opinion on this: Is there an option to totally remove the irrigation-unlimited from HACS and HA and ten reinstall it from zero? What is the right way to do it?

Fairly straightforward. Go to HACS/Irrigation Unlimited
Click on the 3 vertical dots on the top right. Here you are. 
![image](https://github.com/rgc99/irrigation-unlimited-card/assets/20872098/a4f9b42e-4040-4bce-a041-2da244109ee2)
For the card select Frontend to access the list of frontend extensions.

**Comment by rgc99** [comment]
It appears the controller is disabled. If so use the drop down menu to the right to re-enable. Posting the log should reveal answer.

**Comment by Kolia56** [comment]
Thank you for this new version
