### ISSUE TITLE
return_response=True error

### ISSUE THREAD

**Issue by triton51** [rgc99/irrigation-unlimited-card#18]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2024.8.0
**Last working release (if known):**

**Browser and Operating System:**
Firefox, win11
Fully Kiosk, android

**Description of problem:**
Card displays only title bar icons, fails to show any irrigation information, with following error:
"This action requires responses and must be called with return_response=True."

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by rgc99** [comment]
Have you installed the latest version of [Irrigation Unlimited](https://github.com/rgc99/irrigation_unlimited)? It should be 2024.8.0.

**Comment by triton51** [comment]
Yes, my Irrigation Unlimited version is 2024.8.0

**Comment by rgc99** [comment]
The card uses a responding service call to get the configuration. You can test this in HA by going to Developer tools -> Actions and run `Irrigation Unlimited: Get Info`. Responding service calls were introduced in June 2023 so they are a somewhat recent addition. Not all the API's were updated initially to support this new functionality but have since got there.

I need to know the version of HA you are running because this is a possible cause of the problem. This can be found in Settings -> About.

**Comment by triton51** [comment]
Thanks for that, running the Irrigation Unlimited: Get Info command responded with a list of controllers and sequences (as expected I presume?)

My HA version:
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Comment by rgc99** [comment]
I am struggling to reproduce this one. The development systems have been updated to the latest release and have no errors. I could be something with the installation. Perhaps remove and reinstall.

**Comment by triton51** [comment]
I have previous tried removing and reinstalling the companion card, I will try the same with Irrigation Unlimited itself as well.

**Comment by triton51** [comment]
I just removed both Irrigation Unlimited and the companion card, then reinstalled both. 

Error persists.

**Comment by rgc99** [comment]
It is most likely that you have `home-assistant-js-websocket` version 9.2.0 installed. The card requires version 9.3.0 and for some reason this hasn't been updated. Possibly there is a conflict with another package. Not an easy one to solve. Check the log for any install issues.

**Comment by triton51** [comment]
I haven't spotted anything in the log relating to the install of the card, just this error when I attempt to add the card to a dashboard, bring up its config or switch to a dashboard with the card on it (I've used this card for a long time without issue, this problem only recently happened but I can't specify exactly when)

-------
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:45:26 am (1 occurrences)
Last logged: 8:45:26 am

[140553774479920] The action requires responses and must be called with return_response=True
--------

Is the above error related to home-assistant-js-websocket or are they different things? 

> The card requires version 9.3.0 and for some reason this hasn't been updated.

Not entirely sure how to check what version I might have installed, if any.

**Comment by triton51** [comment]
A recent update appears to have resolved this, now working again.
