### ISSUE TITLE
Card not showing any controller and getting error: The action requires responses and must be called with return_response=True

### ISSUE THREAD

**Issue by nirnachmani** [rgc99/irrigation-unlimited-card#22]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:** 2024.8.0

**Last working release (if known):**

**Browser and Operating System:**

Windows, Firefox / Android , HA app

**Description of problem:**

I haven't used the irrigation for a while now as it has been winter (I'm in Australia) and now the card doesn't show any controllers and I get the following error on the screen in a black rectangle on the bottom left: 
```
The action requires responses and must be called with return_response=True
```
It used to work just fine a few months ago and I haven't changed the configuration file. Irrigation Unlimited is installed and working. The card loads as I can see the icons on the top of the card:

![image](https://github.com/user-attachments/assets/8b70697c-f4d7-484a-b82d-d5089e802378)

I have tried deleting and re-installing both the integration and the card and tried using only one controller, but still getting the same issue.

Any ideas? Thanks.

**Comment by nirnachmani** [comment]
I found a bit more information about the issue:

1. I found the following log entry (I initially only looked for irrigation unlimited in the log so didn't find it):

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:54:29 PM (147 occurrences)
Last logged: 10:05:27 PM

    [139734741296336] The action requires responses and must be called with return_response=True
```

Does the card use the websocket api? 

2. Oddly, if I clear the cache in Firefox and then refresh the page 3 times, the card starts working (I can see the controllers and use the card), but then if I refresh again or go into another page and return to the view, it stops working again. This only works with a new view I have created that has only the card - in another view that has some other cards it doesn't. It also doesn't work in Chrome.

**Comment by rgc99** [comment]
This sounds like the same as issue #18. It seemed to resolve itself in the end.

**Comment by rgc99** [comment]
I'm guessing another card is using the old version (9.2.0) of home-assistant-js-websocket and causing a conflict.

**Comment by nirnachmani** [comment]
@rgc99 you are right! Thank you for your help. 

In my case it was the honeycomb-menu card - once I removed it the irrigation unlimited card started working.

I eventually managed to figure out which card caused the conflict (after spending hours looking console errors and websocket traffic which was not helpful) by moving all the cards except the irrigation unlimited card out from the www/community folder, after which the irrigation unlimited card started working. I then copied back card by card, refreshing the browser each time, until I found the culprit.

**Comment by triton51** [comment]
> In my case it was the honeycomb-menu card - once I removed it the irrigation unlimited card started working.

It would appear my issue [#18] was also caused by the honeycomb-menu card, I removed it the same time as some other updates and had assumed the updates had resolved it.

**Comment by nirnachmani** [comment]
If anyone has this issue, Sian from honeycomb-menu provided a fix which can be found here:
[https://github.com/Sian-Lee-SA/honeycomb-menu/issues/86](url). He is using a deprecated call-service instead of fire-dom-event (I am just repeating, I don't really know what this means specifically) and hasn't updated to prevent breaking changes.
