### ISSUE TITLE
GUI Enabling/Disabling zones/sequences confused 

### ISSUE THREAD

**Issue by stomko11** [rgc99/irrigation-unlimited-card#3]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2022.4.1

**Last working release (if known):**
N/A

**Browser and Operating System:**
Android Companion App and Windows 10/Chrome

**Description of problem:**

I have both companion card and standard lovelace card for monitoring of the state of the irrigation in the Gui.
Problem is with using the toggle for disabling the controller. When I am toggling it on either of the cards, the state is not always correctly reflected in companion card, until I refresh the browser (after toggling it). Old lovelace card is always showing true state.

Here is example:
All zones are enabled:
![image](https://user-images.githubusercontent.com/88718231/178916188-5bc0b974-7ff6-4a39-b2d7-bb6a29e668ed.png)

I toggle it in the old card and this happens, which seems OK:
![image](https://user-images.githubusercontent.com/88718231/178916373-b43d779c-fb88-425b-8e66-f564106eacdb.png)

Now I toggle it again in the old card:
![image](https://user-images.githubusercontent.com/88718231/178916500-f6f50021-a5b9-482f-a56f-e8b764043330.png)
As you can see, companion card still says "off" for the controller, and 3 of 5 zones show "enabled"

Now if I just refresh my browser, everything is correctly displayed:
![image](https://user-images.githubusercontent.com/88718231/178916670-0f03a62a-f564-4471-8dba-6319b2ec05fe.png)

When I toggle just main controller in companion card, old card always reports status OK, however companion card does not (e.g. controller stays disabled, some of the zones under it show enabled, some disabled, until I refresh).
I am not observing such issues if I toggle zones in any of the cards, it is always with main controller only.

**Comment by rgc99** [comment]
This should be fixed in the latest release (2022.8.0).

**Comment by stomko11** [comment]
Resolved
