### ISSUE TITLE
Possibility to show card as always expanded

### ISSUE THREAD

**Issue by stomko11** [rgc99/irrigation-unlimited-card#4]
**Is your feature request related to a problem? Please describe.**
This is not related to any bug, just nice to have

**Describe the solution you'd like**
While there are toggles for displaying zones and sequences, it would be nice if it could be configured to preserve options. I would like to have "zones" and "sequences" always expanded. Right now, if I toggle it, they get expanded, but when I refresh/close browser/companion app, and navigate back, it is collapsed again.
Maybe it could be configured in a way:
Zones:
show toggle: yes/no
always expanded: yes/no

Sequences:
show toggle: yes/no
always expanded: yes/no

![image](https://user-images.githubusercontent.com/88718231/178918844-80fb12d4-2c95-4ab5-bae5-7736b43027f3.png)

**Comment by Kolia56** [comment]
I second this idea

**Comment by rgc99** [comment]
Available from release 2022.10.0
