### ISSUE TITLE
Add zone names to the sequences

### ISSUE THREAD

**Issue by kandrzejczak** [rgc99/irrigation-unlimited-card#6]
I think it would be nice to add the zone names in the sequences tab. Now I have to open the zones tab to check what number it is.

![image](https://user-images.githubusercontent.com/13135091/180760110-573506ed-6902-4d01-a1e0-2877617aea95.png)

@rgc99

**Comment by ari-za** [comment]
Good idea

**Comment by nicknol** [comment]
yes, good idea. Would be very convenient :)

**Comment by rgc99** [comment]
Available from release 2022.10.0
