### ISSUE TITLE
Possibility to show/hide controller in the card parameters

### ISSUE THREAD

**Issue by f616** [rgc99/irrigation-unlimited-card#7]
Is there an option to specify which controllers appear in the card?
My use case is, I have two controllers. Would like to configure one card with controller1 and a second card with controller2.
And then show a dashboard to user1 with the card configured with the contoller1 and the same for user2/controller2.

Meaning, user1 should not see the card/dashboard thas has the controller2, and the other way around to user2.

**Comment by rgc99** [comment]
Available from release 2022.10.0
